import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;

import javax.imageio.ImageIO;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * @author roman
 */
public class GraphJPanel extends javax.swing.JPanel {
    /**
     * Creates new form GraphJPanel
     */
    public GraphJPanel() {
        initComponents();
    }
    
    BufferedImage bufImg;
    String imageName;
    int cont = 0;
    Timer t;
    int weigth=0;
    int height=0;

    GraphJPanel(String imageName, int w, int h) {
        this();
        this.imageName = imageName;
        this.weigth=w;
        this.height=h;
           
        t = new javax.swing.Timer(200, new ActionListener() {
            @Override
            public void actionPerformed(final ActionEvent e) {
                //do an icon change
                try {
                    bufImg = ImageIO.read(new File(imageName + ".png"));
                    setSize(bufImg.getWidth() + 50, bufImg.getHeight() + 50);
                } catch (Exception ex) {
                    cont=-2;
                }
                cont++;
                if (cont >= 2) {
                    t.stop();
                }
                if (cont > 0) {
                    setVisible(true);
                }
            }
        });      
        t.start();

    }

    @Override
    public void paint(Graphics g) {
        g.setColor(Color.white);
        g.fillRect(0, 0, weigth * 2, height * 2);
        g.drawImage(bufImg,5, 30, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
